import os
import openai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize OpenAI client
api_key = os.getenv("OPENAI_API_KEY")
if api_key:
    openai.api_key = api_key

def get_explanation(modality, confidence_score, detected_regions):
    """
    Generates an explanation for the segmentation results using OpenAI.

    Args:
        modality (str): The type of scan (CT, CTC, Combined).
        confidence_score (float): The confidence score of the prediction.
        detected_regions (str): Description of detected regions.

    Returns:
        str: The explanation generated by the LLM.
    """
    if not api_key:
        return "⚠️ OpenAI API Key is missing. Please add it to the .env file to enable AI interpretation."

    prompt = f"""
    You are an expert radiologist assistant. 
    A brain segmentation analysis has been performed on a medical image.
    
    scan_type: {modality}
    confidence_score: {confidence_score}
    findings: {detected_regions}
    
    Please provide a concise, clinical interpretation of these results for a doctor. 
    Explain what the confidence score implies and what the findings might suggest. 
    Use professional medical terminology but keep it accessible.
    """

    try:
        response = openai.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful medical AI assistant."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=150,
            temperature=0.7
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"❌ Error generating explanation: {str(e)}"
